on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: zhoubin-datareachable/dc-action@main
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.token5 }}
