on:
  push:
    branches:
      - main
      
defaults:
  run:
    shell: bash
    working-directory: ./App
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          mkdir ~/.kube && mkdir ~/.aws
          cd ~/
          ls
      - name: Set up Node.js
        uses: zhoubin-datareachable/dc-action@main
        with:
          name: "dr_bin_test1"
          username: ${{ github.actor }}
          password: "123456"
          registry: ghcr.io
          tags: "latest"
        
